CREATE TABLE [dbo].[People]
(
    [PersonId] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [FirstName] NVARCHAR(100) NOT NULL,
    [LastName] NVARCHAR(100) NOT NULL,
    [Email] NVARCHAR(255) NULL,
    [Phone] NVARCHAR(20) NULL,
    [CreatedDate] DATETIME2 NOT NULL CONSTRAINT DF_People_CreatedDate DEFAULT (SYSUTCDATETIME()),
    [ModifiedDate] DATETIME2 NOT NULL CONSTRAINT DF_People_ModifiedDate DEFAULT (SYSUTCDATETIME())
);
