CREATE TABLE [dbo].[Roles]
(
    [RoleId] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [RoleName] NVARCHAR(100) NOT NULL,
    [Description] NVARCHAR(500) NULL,
    [CreatedDate] DATETIME2 NOT NULL CONSTRAINT DF_Roles_CreatedDate DEFAULT (SYSUTCDATETIME()),
    [ModifiedDate] DATETIME2 NOT NULL CONSTRAINT DF_Roles_ModifiedDate DEFAULT (SYSUTCDATETIME())
);
